### ISSUE TITLE
Import custom superset roles

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#166]
We need to support extending the superset roles by:

```[tasklist]
### Tasks
- [ ] Create new roles
- [ ] Update existing roles (names and permissions)
- [ ] Allow to automatically assign roles at SSO login
```
