### ISSUE TITLE
Research: Support for CCX courses

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#587]
This issue is intended to track what must be done to support CCX courses. Initial research on CCX courses must be done to determine how they differ from primary courses, their use cases, and the information needed.

```[tasklist]
### Tasks
- [ ] ClickHouse Schema changes needed.
- [ ] ClickHouse functions changes.
- [ ] Changes to the `course_overviews` sink.
- [ ] New sinks needed.
- [ ] New event transformers.
- [ ] New dbt reports and materialized views.
- [ ] Changes to the Instructor Dashboard or if it's needed a new dashboard.
```

**Comment by Ian2012** [comment]
The following PRs are in progress to support CCX courses:

- https://github.com/openedx/event-routing-backends/pull/392: Fixes to CCX related events transformations.
- https://github.com/openedx/aspects-dbt/pull/44 and https://github.com/openedx/tutor-contrib-aspects/pull/607: Fixes an issue extracting the organization from CCX course URLs.

Further research is required

**Comment by Ian2012** [comment]
All PRs merged, waiting for CI to pass here: https://github.com/openedx/tutor-contrib-aspects/pull/619.

@bmtcril Although the CCX courses are supported now, the experience of choosing CCX courses is not a good one. I was thinking of updating the `course_run` filter's dataset so that when courses are filtered by `course_name`, CCX child courses appear as a run of the master courses. Do you see this approach feasible?

**Comment by bmtcril** [comment]
I think that should be handled as part of the mock ups since we don't know how filtering is going to work yet. I think we can close this out since any remaining work is going to be done elsewhere?
